### ISSUE TITLE
id in the results

### ISSUE THREAD

**Issue by JackqqWang** [euagendas/m3inference#14]
Can I ask the id in the results is user id or tweet id?

**Comment by computermacgyver** [comment]
It depends how you're invoking the script, @JackqqWang , but in general the id is the numeric userid of the Twitter user. 

If you pass in your own jsonl data you can make the id anything you want so long as it is unique within the file. The id is not used within the inference process itself. It is only used to connect input data with output data.

All inference happens with the `user` object from Twitter. No tweet information is used.
