### ISSUE TITLE
Support Different Languages Outside the EU?

### ISSUE THREAD

**Issue by swicaksono** [euagendas/m3inference#19]
Hey, thank you for making this project. What awesome and incredible research.
Is the project is also supported in different languages outside the EU? If not, which part of the project can emphasize this. I am interested to research this project.

**Comment by zijwang** [comment]
Hi @swicaksono ! Our focus is languages in EU and, at this moment, we have no plan to expand it to other languages.

**Comment by computermacgyver** [comment]
Thanks @swicaksono for reaching out. Just a quick note that while we focused on "the 32 most spoken languages in Europe," this includes Arabic and many languages beyond the EU. The research project that funded this was focused on the EU, and while I am passionate about broader cross-language support (currently doing a lot of work with various Indian languages) we don't have the funding to expand m3 at present.

The full list of languages supported is:
ar - Arabic
bg - Bulgarian
bs - Bosnian
cs - Czech
cy - Welsh
da - Danish
de - German
el - Greek
en - English
es - Spanish
et - Estonian
eu - Basque
fi - Finnish
fr - French
ga - Irish
hr - Croatian
hu - Hungarian
is - Icelandic
it - Italian
lt - Lithuanian
lv - Latvian
mt - Maltese
nl - Dutch
no - Norwegian
pl - Polish
pt - Portuguese
rm - Romansh
ro - Romanian
ru - Russian
sk - Slovak
sl - Slovenian
tr - Turkish
un - Unknown
