### ISSUE TITLE
Commercial use

### ISSUE THREAD

**Issue by angelgfo** [euagendas/m3inference#24]
Best regards. My compliments. 
Is it possible to use the python code or the python library for a commercial project?  What are the restrictions or requirements?
Thanks.

**Comment by computermacgyver** [comment]
Hi @angelgfo , the code is under the GNU Affero General Public License v3.0, per the [LICENSE file](https://github.com/euagendas/m3inference/blob/master/LICENSE) . This license requires whatever software/service is using the library to be similarly licensed, i.e., the code of projects using m3inference must be open-source.
