### ISSUE TITLE
Improve requests speed

### ISSUE THREAD

**Issue by eslamahmed235** [euagendas/m3inference#27]
Hello 
I already used M3inferince and work well. but in large scale of data it's not fast enough. It takes an average 1.3 second for each account while running on kaggel GPU. 
If there are any advice or technique to speed up it's progress.

**Comment by computermacgyver** [comment]
I'm glad you're finding m3 useful. We welcome pull requests and optimizations. The main thing I would do is pack images into batches. There's not enough detail here on how you're using m3, but if you do all your preprocessing and downloading of the images first, m3 will batch process the inference stage.
