### ISSUE TITLE
Output file options

### ISSUE THREAD

**Issue by Terela62** [euagendas/m3inference#28]
I am using M3 for a research project and will be combining the output with other data from Twitter. Is it possible to output the results into something more manageable than the print screen output after running the code? The readme does reference the output format but not sure where to look next.

**Comment by zijwang** [comment]
@Terela62 thanks for your interest in M3. Could you provide a minimal example why it is "print screen"?

**Comment by Terela62** [comment]
@zijwang It has just dawned on me that it outputs an OrderedDict() and I can save using 

```
with open('results.json', 'w') as f:
    json.dump(pred, f)
```

Thank you for your quick response though
