### ISSUE TITLE
Problems with installation 

### ISSUE THREAD

**Issue by BrittaRude** [euagendas/m3inference#29]
Hello, 

I am trying to install m3inference through "pip install m3inference", but I get an error code (see below). I tried several things to fix this, but it does not resolve the issue. I believe it has something to do with the  "pycld2" - when I tried to install it separately, it did also not work. 

Thanks in advance: 

(base) C:\Users\Rude>pip install m3inference
Collecting m3inference
  Using cached m3inference-1.1.5-py3-none-any.whl (58 kB)
Requirement already satisfied: tqdm in c:\users\rude\appdata\local\continuum\ana
conda3\lib\site-packages (from m3inference) (4.28.1)
Collecting pycld2>=0.31
  Using cached pycld2-0.41.tar.gz (41.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: torch>=1.0.0 in c:\users\rude\appdata\local\conti
nuum\anaconda3\lib\site-packages (from m3inference) (1.10.1)
Requirement already satisfied: Pillow in c:\users\rude\appdata\local\continuum\a
naconda3\lib\site-packages (from m3inference) (5.3.0)
Requirement already satisfied: pandas>=0.20 in c:\users\rude\appdata\local\conti
nuum\anaconda3\lib\site-packages (from m3inference) (1.3.4)
Requirement already satisfied: torchvision>=0.2.2 in c:\users\rude\appdata\local
\continuum\anaconda3\lib\site-packages (from m3inference) (0.11.2)
Requirement already satisfied: rauth in c:\users\rude\appdata\roaming\python\pyt
hon37\site-packages (from m3inference) (0.7.3)
Requirement already satisfied: requests in c:\users\rude\appdata\local\continuum
\anaconda3\lib\site-packages (from m3inference) (2.21.0)
Requirement already satisfied: numpy>=1.13 in c:\users\rude\appdata\roaming\pyth
on\python37\site-packages (from m3inference) (1.21.4)
Requirement already satisfied: pytz>=2017.3 in c:\users\rude\appdata\local\conti
nuum\anaconda3\lib\site-packages (from pandas>=0.20->m3inference) (2018.7)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\rude\appdata\l
ocal\continuum\anaconda3\lib\site-packages (from pandas>=0.20->m3inference) (2.7
.5)
Requirement already satisfied: typing-extensions in c:\users\rude\appdata\local\
continuum\anaconda3\lib\site-packages (from torch>=1.0.0->m3inference) (4.0.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\rude\appdata\lo
cal\continuum\anaconda3\lib\site-packages (from requests->m3inference) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\users\rude\appdata\local\con
tinuum\anaconda3\lib\site-packages (from requests->m3inference) (2.8)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\rude\appdata\local
\continuum\anaconda3\lib\site-packages (from requests->m3inference) (2021.5.30)
Requirement already satisfied: urllib3<1.25,>=1.21.1 in c:\users\rude\appdata\lo
cal\continuum\anaconda3\lib\site-packages (from requests->m3inference) (1.24.1)
Requirement already satisfied: six>=1.5 in c:\users\rude\appdata\local\continuum
\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas>=0.20->m3infer
ence) (1.12.0)
Building wheels for collected packages: pycld2
  Building wheel for pycld2 (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\rude\appdata\local\continuum\anaconda3\python.exe' -u -c '
import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rude\\Ap
pData\\Local\\Temp\\5\\pip-install-3n3kiofw\\pycld2_04bebb99f5e4481caa01025a1abb
1b1f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rude\\AppData\\Local\\Temp\\5\\pip
-install-3n3kiofw\\pycld2_04bebb99f5e4481caa01025a1abb1b1f\\setup.py'"'"';f = ge
tattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else
 io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().re
place('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'
exec'"'"'))' bdist_wheel -d 'C:\Users\Rude\AppData\Local\Temp\5\pip-wheel-7as7f8
gd'
       cwd: C:\Users\Rude\AppData\Local\Temp\5\pip-install-3n3kiofw\pycld2_04beb
b99f5e4481caa01025a1abb1b1f\
  Complete output (10 lines):
  running bdist_wheel
  The [wheel] section is deprecated. Use [bdist_wheel] instead.
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\pycld2
  copying pycld2\__init__.py -> build\lib.win-amd64-3.7\pycld2
  running build_ext
  error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsof
t C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
  ----------------------------------------
  ERROR: Failed building wheel for pycld2
  Running setup.py clean for pycld2
Failed to build pycld2
Installing collected packages: pycld2, m3inference
    Running setup.py install for pycld2 ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\rude\appdata\local\continuum\anaconda3\python.exe' -u -c
 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Rude\\
AppData\\Local\\Temp\\5\\pip-install-3n3kiofw\\pycld2_04bebb99f5e4481caa01025a1a
bb1b1f\\setup.py'"'"'; __file__='"'"'C:\\Users\\Rude\\AppData\\Local\\Temp\\5\\p
ip-install-3n3kiofw\\pycld2_04bebb99f5e4481caa01025a1abb1b1f\\setup.py'"'"';f =
getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) el
se io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().
replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'
"'exec'"'"'))' install --record 'C:\Users\Rude\AppData\Local\Temp\5\pip-record-3
t8c0_3x\install-record.txt' --single-version-externally-managed --compile --inst
all-headers 'c:\users\rude\appdata\local\continuum\anaconda3\Include\pycld2'
         cwd: C:\Users\Rude\AppData\Local\Temp\5\pip-install-3n3kiofw\pycld2_04b
ebb99f5e4481caa01025a1abb1b1f\
    Complete output (11 lines):
    running install
    c:\users\rude\appdata\local\continuum\anaconda3\lib\site-packages\setuptools
\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprec
ated. Use build and pip and other standards-based tools.
      setuptools.SetuptoolsDeprecationWarning,
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\pycld2
    copying pycld2\__init__.py -> build\lib.win-amd64-3.7\pycld2
    running build_ext
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Micros
oft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\rude\appdata\local\cont
inuum\anaconda3\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys
.argv[0] = '"'"'C:\\Users\\Rude\\AppData\\Local\\Temp\\5\\pip-install-3n3kiofw\\
pycld2_04bebb99f5e4481caa01025a1abb1b1f\\setup.py'"'"'; __file__='"'"'C:\\Users\
\Rude\\AppData\\Local\\Temp\\5\\pip-install-3n3kiofw\\pycld2_04bebb99f5e4481caa0
1025a1abb1b1f\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file_
_) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setu
p; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close()
;exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Rude\
AppData\Local\Temp\5\pip-record-3t8c0_3x\install-record.txt' --single-version-ex
ternally-managed --compile --install-headers 'c:\users\rude\appdata\local\contin
uum\anaconda3\Include\pycld2' Check the logs for full command output.

(base) C:\Users\Rude>

**Comment by zijwang** [comment]
The log already reveals what’s needed :)

error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Micros
oft C++ Build Tools": 

btw there is no guarantee that the m3 package will work on Windows. You are welcome to try, but we’d recommend running it on a *nix machine.

**Comment by zijwang** [comment]
Close the issue for now. Please reopen in case you have further questions.
