### ISSUE TITLE
Question about training procedure code

### ISSUE THREAD

**Issue by icmpnorequest** [euagendas/m3inference#3]
Hi team,
Thank you so much for your great work.
I was wondering could you please upload the training procedure code? I read the uploaded code but didn't find the code about multi-task classification procedure. I only found the code about evaluation.
Thanks in advance.

**Comment by computermacgyver** [comment]
The training procedure is described in the published paper, which is freely available at https://arxiv.org/abs/1905.05961 . 

The training code isn't online at present, but we can look into this if needed.
